#+TITLE: Try and demo multiple emacs configs

* Idea

You can =cd= to any directory and use =e= to launch =emacs= with this directory
instead of =~/.emacs.d=.  There is also =ed= and =ec= to work with the daemon
and client.

* How to use it

Clone the repo

#+begin_src shell
git clone https://github.com/philippecarphin/emacs-configs
#+end_src

Add the repo's =./bin= directory to your =PATH= environment variable

#+begin_src shell
source emacs-configs/source-me.sh
#+end_src

You can =cd= to any directory that contains an =init.el= file and run the
command =ed= (emacs with directory).  This starts emacs using =$PWD= instead of
=~/.emacs.d=.

* Extra configs

It's all the same executable with links pointing to it.

Doing =e[d][v][h][b]= (ex =edh= or =evb=) will add certain things.

** v : evil-mode
If you can't live without evil mode, use =ecv= instead.  It will do the same
thing: load emacs with the PWD as the user config directory but it will also
load =evil-mode=.

** d : daemon

Launch with =--daemon=$(basename $PWD)=.  Use =ec= (=emacsclient -s $(basename
$PWD)=) to connect to this daemon.

** h : Helpers : Helm and Which-key

Helm is really useful completion help for opening files and entering commands

Which-key gives you a pop up with possible keys to complete sequences.

** b : Bare necessities

Stock emacs can hurt your eyes, add 'b' to to the command to add minor behavior
tweaks and loading of =misterioso= color theme.
  
* Use cases

** Demonstrating simplicity

If I want to show "Look what little configuration I need to do this cool thing",
I might try it with =ev= just to have emacs look ultra stock but adding
evil-mode because I can't live without it.

** Demonstrating features

If I want to show cool features without worrying about how anything is
configured, I'll use =evhb= to get a good looking emacs with evil-mode and helm
so I can fly while I demonstrate things.

